/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Usuario' at '11/11/16 11:52' with Gradle 2.14.1
 *
 * @author Usuario, @date 11/11/16 11:52
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
